- hosts: all
  pre_tasks:
    - name: Use buildset registry
      include_role:
        name: use-buildset-registry
  roles:
    - build-docker-image
  tasks:
    - name: Return images to zuul
      include_tasks: _return-image.yml
      loop: "{{ docker_images }}"
      loop_control:
        loop_var: zj_image
