---
# Copyright 2019, SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    check:
      jobs:
        - opendev-buildset-registry
        - openstack-helm-images-aio-monitoring
        - openstack-helm-images-aio-logging
#        - openstack-helm-images-compute-kit-train-ubuntu_bionic
#        - openstack-helm-images-cinder-train-ubuntu_bionic
#        - openstack-helm-images-horizon-train-ubuntu_bionic
        - openstack-helm-images-compute-kit-ussuri-ubuntu_bionic
        - openstack-helm-images-cinder-ussuri-ubuntu_bionic
        - openstack-helm-images-compute-kit-victoria-ubuntu_focal
        - openstack-helm-images-cinder-victoria-ubuntu_focal
        - openstack-helm-images-compute-kit-wallaby-ubuntu_focal
        - openstack-helm-images-cinder-wallaby-ubuntu_focal
    gate:
      jobs:
        - opendev-buildset-registry
        - openstack-helm-images-aio-monitoring
        - openstack-helm-images-aio-logging
#        - openstack-helm-images-compute-kit-train-ubuntu_bionic
#        - openstack-helm-images-cinder-train-ubuntu_bionic
#        - openstack-helm-images-horizon-train-ubuntu_bionic
        - openstack-helm-images-compute-kit-ussuri-ubuntu_bionic
        - openstack-helm-images-cinder-ussuri-ubuntu_bionic
        - openstack-helm-images-compute-kit-victoria-ubuntu_focal
        - openstack-helm-images-cinder-victoria-ubuntu_focal
        - openstack-helm-images-compute-kit-wallaby-ubuntu_focal
        - openstack-helm-images-cinder-wallaby-ubuntu_focal
    periodic:
      jobs:
        - opendev-buildset-registry
        - openstack-helm-images-aio-monitoring
        - openstack-helm-images-aio-logging
 #       - openstack-helm-images-compute-kit-train-ubuntu_bionic
 #       - openstack-helm-images-cinder-train-ubuntu_bionic
 #       - openstack-helm-images-horizon-train-ubuntu_bionic
        - openstack-helm-images-compute-kit-ussuri-ubuntu_bionic
        - openstack-helm-images-cinder-ussuri-ubuntu_bionic
        - openstack-helm-images-compute-kit-victoria-ubuntu_focal
        - openstack-helm-images-cinder-victoria-ubuntu_focal
        - openstack-helm-images-compute-kit-wallaby-ubuntu_focal
        - openstack-helm-images-cinder-wallaby-ubuntu_focal
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3

# This takes the same structure as other infra jobs.
# This dict keyname matter. See also job definition for more explanations.
- secret:
    name: openstack-helm-dockerhub
    data:
      username: !encrypted/pkcs1-oaep
        - RToLVrVSLl4ih5OcfL/AnemDTVLsg+TLijXniZ+MPK8h332v813CRMH2vVFf7zZxVw+fA
          rjVjonkSaNkseXlGd9+psv8gRvxV5qg63emxFtpARSJiS7HgyOdBUy4ZhsrweF7F1KfH1
          LNKXoaYdDCn7UcP/YaqYBkr2UQ/F0t7Yu6ACjdQYUr3FKh8XfAhrUtcc+uAv7broiIxKq
          LRi7UTXa1NEpA0rH0dLep5eNKQBpiXo/7cF3fCIMJ8oCGTZToaUkJfoqax96g/oncpf+a
          wQvlML5WN7YrB5Fi9RkylOVkCOUJcO5HUeFWpfcnPsvwELulpIKnxLlLxR94ZM0ZmCNcI
          of8yyEAoxCOHOLYZcKNSKjWl6rMmKElTEeedqiJniBSWRwxz7/pj27fQKHDJPfPSXgfqU
          GNkOLBHdK03idEL39G3rvPKt+lR5xV29iX5EH03VoJoKUBoeggxkC9/3/DcjZ2M8hUD7Q
          IM5UjMV1Lgo5apodGZu5tUfaoCMPN4xHCzI2vZZ08ZP5952opp9A4c/OLKOUDHV63qei5
          e2SA8BBtvz/eiUWhLhwMHZK18XqsB8vLZNeO8BUDS5oOfw8YYaEfm3t3hqXNn7khWNlT6
          MAn3KrFsslsP7ENNFHIxIy4eVXDoDtG90CZWReM2cLdGnbQa2YLdwjjPWN6tlc=
      password: !encrypted/pkcs1-oaep
        - GPDRxEQwaaFK7427kQByOYoEzcAXvNkGJKcBhoiwXPZ2V2taDH3vZWMDByfWLPDp7HTNp
          MHIJqeGE446EtO+eGmDNFuXHDCbwEwBIGd27QNNKGdmYAXlrU5dxKaoChra+8gcxsXYxJ
          FlNlfdMqz3Dt+ZTA7f68db9T/hBm2PDAuJml2dHsHCQg5yFljZADcNvbRV4PPf/9SylMa
          wJPI6XAbzo/bTBnMmsn5u6ovlrIBkO+OMdYQ2Bd22GZkOoUo04M7mz10kPTeSCaGI10b2
          LR1eN7thS+1ViB+VqoecZ3yOf3KgU9KmVsLkmEGfJUjBXV7dfWZsCvzSM/72WE6yjybQ3
          iwhpiKVr8EmZAePgiEvjfI/eFcDp+BCfn7fjA5vpJ1qhYXx6WX+IebC8bQ/SfDBXz2kgI
          kgeCOCqszqR6z/lF//j6ttIIKMGM/OV8AVN8mSwqbx9x6W9y0wFX+Qr4awDcHV0eVJelA
          aYZxpgceCShEZp54yIVNjDoe01m8UpDDSSj7qtaehX+5U8vKd6lWOf13YEVIfaYUCoNaK
          Zp1xo0hJ2T2/8FGY/+sgZtjXJ4SETyTTw0kzQy/Ias8h63YIsDi7cQ2Yx48rGtugxArTD
          Kkrob2q6wFLBIutk8NgfXUy0oLClufRmHidne4XB0VLHeykuxKjiujGm+O9AcQ=

# In docker_images:
# `context` is the folder in osh-images
# `repository` is the repo on dockerhub
# `tags` is a list of the tags when promoted
#   (images are published with change id)
# `dockerfile`. Explicit.
- job:
    name: openstack-helm-images-build
    parent: build-docker-image
    run: zuul.d/playbooks/build.yml
    match-on-config-updates: false
    dependencies:
      - name: opendev-buildset-registry
    abstract: true
    # Minimum version required is 2.8.
    # When default in zuul moves to 2.8, remove
    # this line.
    # See also: https://zuul-ci.org/docs/zuul/user/config.html#attr-job.ansible-version
    ansible-version: 2.8
    description: |
      This job is building a docker image for
      OpenStack-Helm usage.
      Image specific tests can be added by
      running a post script on the relevant
      jobs.
    irrelevant-files:
      - ^\.git.*
      - ^.*\.(example|md|rst)$
      - ^doc/.*
      - ^releasenotes/.*
    timeout: 3600

- job:
    name: openstack-helm-images-upload
    parent: openstack-helm-images-build
    run:
      - zuul.d/playbooks/build.yml
      - zuul.d/playbooks/upload.yml
    match-on-config-updates: false
    dependencies:
      - name: opendev-buildset-registry
    abstract: true
    ansible-version: 2.8
    secrets:
      name: docker_credentials
      secret: openstack-helm-dockerhub
    timeout: 3600

- job:
    name: openstack-helm-images-promote
    parent: promote-docker-image
    abstract: true
    ansible-version: 2.8
    secrets:
      name: docker_credentials
      secret: openstack-helm-dockerhub
      pass-to-parent: true
    timeout: 3600

# Image testing jobs inheriting from osh and osh-infra jobs running against
# particular image or set of images.
- job:
    name: openstack-helm-images-aio-monitoring
    parent: openstack-helm-infra-aio-monitoring
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-prometheus-openstack-exporter
        soft: true
      - name: openstack-helm-images-build-osh-selenium
        soft: true
      - name: openstack-helm-images-build-node-problem-detector
        soft: true
      - name: openstack-helm-images-build-nagios
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-prometheus-openstack-exporter
        soft: true
      - name: openstack-helm-images-upload-osh-selenium
        soft: true
      - name: openstack-helm-images-upload-node-problem-detector
        soft: true
      - name: openstack-helm-images-upload-nagios
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
    files:
      - prometheus-openstack-exporter/.*
      - zuul.d/prometheus-openstack-exporter.yaml
      - osh-selenium/.*
      - zuul.d/osh-selenium.yaml
      - node-problem-detector/.*
      - zuul.d/node-problem-detector.yaml
      - nagios/.*
      - zuul.d/nagios.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-aio-logging
    parent: openstack-helm-infra-aio-logging
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-fluentd
        soft: true
      - name: openstack-helm-images-build-elasticsearch-s3
        soft: true
      - name: openstack-helm-images-build-osh-selenium
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-fluentd
        soft: true
      - name: openstack-helm-images-upload-elasticsearch-s3
        soft: true
      - name: openstack-helm-images-upload-osh-selenium
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
    files:
      - fluentd/.*
      - zuul.d/fluentd.yaml
      - elasticsearch-s3/.*
      - zuul.d/elasticsearch-s3.yaml
      - osh-selenium/.*
      - zuul.d/osh-selenium.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-compute-kit-train-ubuntu_bionic
    parent: openstack-helm-compute-kit-train-ubuntu_bionic
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-openvswitch
        soft: true
      - name: openstack-helm-images-build-openstack-loci-train-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-build-mariadb
        soft: true
      - name: openstack-helm-images-build-libvirt
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-openvswitch
        soft: true
      - name: openstack-helm-images-upload-openstack-loci-train-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-upload-mariadb
        soft: true
      - name: openstack-helm-images-upload-libvirt
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
    files:
      - openvswitch/.*
      - zuul.d/openvswitch.yaml
      - ^openstack/loci/.*
      - zuul.d/openstack-loci.yaml
      - mariadb/.*
      - zuul.d/mariadb.yaml
      - libvirt/.*
      - zuul.d/libvirt.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-cinder-train-ubuntu_bionic
    parent: openstack-helm-cinder-train-ubuntu_bionic
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-openstack-loci-train-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-build-mariadb
        soft: true
      - name: openstack-helm-images-upload-openstack-loci-train-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-mariadb
        soft: true
    files:
      - ^openstack/loci/.*
      - zuul.d/openstack-loci.yaml
      - mariadb/.*
      - zuul.d/mariadb.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-horizon-train-ubuntu_bionic
    parent: openstack-helm-horizon-train-ubuntu_bionic
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-osh-selenium
        soft: true
      - name: openstack-helm-images-build-openstack-loci-train-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-osh-selenium
        soft: true
      - name: openstack-helm-images-upload-openstack-loci-train-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
    files:
      - osh-selenium/.*
      - zuul.d/osh-selenium.yaml
      - ^openstack/loci/.*
      - zuul.d/openstack-loci.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-compute-kit-ussuri-ubuntu_bionic
    parent: openstack-helm-compute-kit-ussuri-ubuntu_bionic
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-openvswitch
        soft: true
      - name: openstack-helm-images-build-openstack-loci-ussuri-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-build-mariadb
        soft: true
      - name: openstack-helm-images-build-libvirt
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-openvswitch
        soft: true
      - name: openstack-helm-images-upload-openstack-loci-ussuri-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-upload-mariadb
        soft: true
      - name: openstack-helm-images-upload-libvirt
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
    files:
      - openvswitch/.*
      - zuul.d/openvswitch.yaml
      - ^openstack/loci/.*
      - zuul.d/openstack-loci.yaml
      - mariadb/.*
      - zuul.d/mariadb.yaml
      - libvirt/.*
      - zuul.d/libvirt.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-cinder-ussuri-ubuntu_bionic
    parent: openstack-helm-cinder-ussuri-ubuntu_bionic
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-openstack-loci-ussuri-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-build-mariadb
        soft: true
      - name: openstack-helm-images-upload-openstack-loci-ussuri-ubuntu_bionic
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-mariadb
        soft: true
    files:
      - ^openstack/loci/.*
      - zuul.d/openstack-loci.yaml
      - mariadb/.*
      - zuul.d/mariadb.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-compute-kit-victoria-ubuntu_focal
    parent: openstack-helm-compute-kit-victoria-ubuntu_focal
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-openvswitch
        soft: true
      - name: openstack-helm-images-build-openstack-loci-victoria-ubuntu_focal
        soft: true
      - name: openstack-helm-images-build-mariadb
        soft: true
      - name: openstack-helm-images-build-libvirt
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-openvswitch
        soft: true
      - name: openstack-helm-images-upload-openstack-loci-victoria-ubuntu_focal
        soft: true
      - name: openstack-helm-images-upload-mariadb
        soft: true
      - name: openstack-helm-images-upload-libvirt
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
    files:
      - openvswitch/.*
      - zuul.d/openvswitch.yaml
      - ^openstack/loci/.*
      - zuul.d/openstack-loci.yaml
      - mariadb/.*
      - zuul.d/mariadb.yaml
      - libvirt/.*
      - zuul.d/libvirt.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-cinder-victoria-ubuntu_focal
    parent: openstack-helm-cinder-victoria-ubuntu_focal
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-openstack-loci-victoria-ubuntu_focal
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-build-mariadb
        soft: true
      - name: openstack-helm-images-upload-openstack-loci-victoria-ubuntu_focal
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-mariadb
        soft: true
    files:
      - ^openstack/loci/.*
      - zuul.d/openstack-loci.yaml
      - mariadb/.*
      - zuul.d/mariadb.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-compute-kit-wallaby-ubuntu_focal
    parent: openstack-helm-compute-kit-wallaby-ubuntu_focal
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-openvswitch
        soft: true
      - name: openstack-helm-images-build-openstack-loci-wallaby-ubuntu_focal
        soft: true
      - name: openstack-helm-images-build-mariadb
        soft: true
      - name: openstack-helm-images-build-libvirt
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-openvswitch
        soft: true
      - name: openstack-helm-images-upload-openstack-loci-wallaby-ubuntu_focal
        soft: true
      - name: openstack-helm-images-upload-mariadb
        soft: true
      - name: openstack-helm-images-upload-libvirt
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
    files:
      - openvswitch/.*
      - zuul.d/openvswitch.yaml
      - ^openstack/loci/.*
      - zuul.d/openstack-loci.yaml
      - mariadb/.*
      - zuul.d/mariadb.yaml
      - libvirt/.*
      - zuul.d/libvirt.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml

- job:
    name: openstack-helm-images-cinder-wallaby-ubuntu_focal
    parent: openstack-helm-cinder-wallaby-ubuntu_focal
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-openstack-loci-wallaby-ubuntu_focal
        soft: true
      - name: openstack-helm-images-build-minikube-aio
        soft: true
      - name: openstack-helm-images-build-mariadb
        soft: true
      - name: openstack-helm-images-upload-openstack-loci-wallaby-ubuntu_focal
        soft: true
      - name: openstack-helm-images-upload-minikube-aio
        soft: true
      - name: openstack-helm-images-upload-mariadb
        soft: true
    files:
      - ^openstack/loci/.*
      - zuul.d/openstack-loci.yaml
      - mariadb/.*
      - zuul.d/mariadb.yaml
      - minikube-aio/.*
      - zuul.d/minikube-aio.yaml
